# Generated by Django 6.0 on 2025-12-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cream_color', models.CharField(choices=[('PINK', 'Pink'), ('BLUE', 'Blue'), ('BEIGE', 'Beige')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=3, help_text='Minimum 3 – Maximum 24')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('IMA', 'Ima (Small)'), ('RUBI', 'Rubi (Large)'), ('LASSIE', 'Lassie (Double)')], max_length=10)),
                ('flavor', models.CharField(choices=[('MEAT', 'Meat'), ('CHICKEN', 'Chicken'), ('TUNA', 'Tuna')], max_length=10)),
                ('animal_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=3)),
                ('cream_color', models.CharField(choices=[('PINK', 'Pink'), ('BLUE', 'Blue'), ('BEIGE', 'Beige')], max_length=5)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.PositiveIntegerField(help_text='Pet age (integer number)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
