# Generated by Django 6.0 on 2025-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='decoration_color',
            field=models.CharField(choices=[('PINK', 'Pink'), ('BLUE', 'Blue')], default='PINK', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavor',
            field=models.CharField(choices=[('MEAT', 'Meat'), ('CHICKEN', 'Chicken'), ('TUNA', 'Tuna')], max_length=7),
        ),
        migrations.AlterField(
            model_name='cake',
            name='pet_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cake',
            name='size',
            field=models.CharField(choices=[('IMA', 'Ima (Small)'), ('RUBI', 'Rubi (Large)'), ('LASSIE', 'Lassie (Double)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='muffin',
            name='quantity',
            field=models.PositiveIntegerField(default=6, help_text='Minimum 6 – Maximum 24'),
        ),
    ]
