# Generated by Django 6.0 on 2026-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha Bloqueada')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Motivo (Opcional)')),
            ],
            options={
                'verbose_name': 'Fecha Bloqueada',
                'verbose_name_plural': 'Fechas Bloqueadas (Vacaciones/Feriados)',
            },
        ),
    ]
