# Generated by Django 6.0 on 2026-01-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles Personalizados'),
        ),
    ]
